// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Enumerates capture devices. Returns NULL if the audio backend is
/// unavailable, which is a normal outcome on a headless machine and not an
/// error worth crashing over. Free with oaa_device_list_free.
@ffi.Native<ffi.Pointer<oaa_device_list> Function()>()
external ffi.Pointer<oaa_device_list> oaa_devices_enumerate();

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<oaa_device_list>)>()
external int oaa_device_list_count(ffi.Pointer<oaa_device_list> list);

@ffi.Native<
  ffi.Pointer<oaa_device_info> Function(
    ffi.Pointer<oaa_device_list>,
    ffi.Uint32,
  )
>()
external ffi.Pointer<oaa_device_info> oaa_device_list_at(
  ffi.Pointer<oaa_device_list> list,
  int index,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<oaa_device_list>)>()
external void oaa_device_list_free(ffi.Pointer<oaa_device_list> list);

/// ------------------------------------------------------------------------ */
/// /* Lifecycle                                                                 */
/// /* ------------------------------------------------------------------------
@ffi.Native<ffi.Int32 Function()>()
external int oaa_abi_version();

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> oaa_version_string();

/// Fills `cfg` with defaults. Call this before overriding fields, so that
/// adding a field to oaa_config does not silently leave it at zero in every
/// existing caller.
@ffi.Native<ffi.Void Function(ffi.Pointer<oaa_config>)>()
external void oaa_config_defaults(ffi.Pointer<oaa_config> cfg);

@ffi.Native<ffi.Pointer<oaa_engine> Function(ffi.Pointer<oaa_config>)>()
external ffi.Pointer<oaa_engine> oaa_engine_create(ffi.Pointer<oaa_config> cfg);

@ffi.Native<ffi.Void Function(ffi.Pointer<oaa_engine>)>()
external void oaa_engine_destroy(ffi.Pointer<oaa_engine> engine);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<oaa_engine>)>()
external int oaa_engine_start(ffi.Pointer<oaa_engine> engine);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<oaa_engine>)>()
external int oaa_engine_stop(ffi.Pointer<oaa_engine> engine);

/// Clears every integrating measurement — integrated loudness, LRA, all the
/// "max since reset" peaks, the clip counters — and restarts the elapsed clock.
/// Momentary values are left alone; they describe the signal, not the session.
@ffi.Native<ffi.Void Function(ffi.Pointer<oaa_engine>)>()
external void oaa_engine_reset(ffi.Pointer<oaa_engine> engine);

/// Reset automatically when the signal returns after a silence.
///
/// This is the engine's whole contribution to the LUFS time modes, and it is
/// here rather than above the engine because silence is a property of audio and
/// not of a host: one implementation serves a plugin in a DAW and a sound card
/// both, and two would eventually disagree about when a track began. The three
/// other modes need a playhead, so they are the caller's business — `engine/`
/// does not learn what a DAW is.
///
/// With this enabled, a block whose highest magnitude is below
/// OAA_SILENCE_FLOOR accumulates towards OAA_SILENCE_HOLD_SECONDS; the first
/// block above the floor once that has expired resets exactly as
/// oaa_engine_reset would, *before* that block is measured. Before rather than
/// after, because a track whose loudest sample is in its first block would
/// otherwise have that peak cleared by its own reset — a true-peak reading that
/// is wrong only for material that opens on a transient, which is most of it.
///
/// Off by default, and off is what every existing caller wants: file analysis
/// measures a file whole, and a reset in the middle of one would report a
/// different programme than the one that was asked for.
///
/// Idempotent, and safe to call while running.
@ffi.Native<ffi.Void Function(ffi.Pointer<oaa_engine>, ffi.Int32)>()
external void oaa_engine_set_silence_reset(
  ffi.Pointer<oaa_engine> engine,
  int enabled,
);

/// The stable address of this engine's snapshot. Valid from create() until
/// destroy(), and it never moves. Call it once and keep the pointer; the
/// contents are only meaningful after oaa_snapshot_acquire().
@ffi.Native<ffi.Pointer<oaa_snapshot> Function(ffi.Pointer<oaa_engine>)>()
external ffi.Pointer<oaa_snapshot> oaa_snapshot_buffer(
  ffi.Pointer<oaa_engine> engine,
);

/// Refresh the snapshot from the analysis thread and return its generation.
///
/// This is the only function called every frame, so it is the only one whose
/// cost is worth arguing about. It is a seqlock read: an atomic load, a memcpy
/// of the snapshot — about 15 kB, most of it the scope and the spectrum — and a
/// second atomic load to confirm no writer intervened. It never blocks the
/// analysis thread and it never waits on a mutex.
///
/// Fifteen kilobytes at 120 fps is under 2 MB/s and roughly a microsecond a
/// frame, which is the argument for copying the whole thing rather than growing
/// a second, narrower path for the modules that only want one number. Two ways
/// to read a measurement is two ways for them to disagree.
///
/// Returns the same value as the previous call when nothing new was published,
/// which is the caller's cue to skip repainting.
@ffi.Native<ffi.Uint64 Function(ffi.Pointer<oaa_engine>)>()
external int oaa_snapshot_acquire(ffi.Pointer<oaa_engine> engine);

/// Measure `frames` frames of interleaved float audio and publish the result.
///
/// Only valid when the engine was created with OAA_SOURCE_PUSH; anything else
/// returns OAA_ERR_WRONG_STATE rather than quietly mixing pushed audio into a
/// stream that a device is already driving.
///
/// Synchronous: on return the snapshot reflects these samples. Any block size is
/// accepted, and the measurements do not depend on it — the 400 ms and 3 s
/// windows are counted in samples internally, so pushing an hour in one call and
/// pushing it in 512-frame chunks produce identical readings. The conformance
/// suite relies on exactly that.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<oaa_engine>,
    ffi.Pointer<ffi.Float>,
    ffi.Uint32,
  )
>()
external int oaa_engine_push(
  ffi.Pointer<oaa_engine> engine,
  ffi.Pointer<ffi.Float> interleaved,
  int frames,
);

/// The address of each array field inside a snapshot.
///
/// These exist so that a consumer can build a typed view over the arrays
/// without knowing their byte offsets. dart:ffi can read the scalars through a
/// generated struct definition perfectly well, but the array fields need to
/// reach the canvas as a flat Float32List — `Canvas.drawRawPoints` and
/// `Vertices.raw` take one directly, and going through per-element accessors
/// instead would put 512 bounds-checked loads on the paint path where a single
/// pointer would do.
///
/// Asking the compiler for the offset rather than computing it in Dart is the
/// whole point. A struct layout that differs between the compiler that built
/// the library and the assumptions baked into the bindings does not crash — it
/// reads the wrong field and displays a plausible number, which is the failure
/// mode this project can least afford.
///
/// Call once, at startup, and keep the views: the snapshot never moves.
@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<oaa_snapshot>)>()
external ffi.Pointer<ffi.Float> oaa_snapshot_peak(
  ffi.Pointer<oaa_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<oaa_snapshot>)>()
external ffi.Pointer<ffi.Float> oaa_snapshot_rms(
  ffi.Pointer<oaa_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<oaa_snapshot>)>()
external ffi.Pointer<ffi.Float> oaa_snapshot_vu(
  ffi.Pointer<oaa_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Uint32> Function(ffi.Pointer<oaa_snapshot>)>()
external ffi.Pointer<ffi.Uint32> oaa_snapshot_clip(
  ffi.Pointer<oaa_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<oaa_snapshot>)>()
external ffi.Pointer<ffi.Float> oaa_snapshot_spectrum(
  ffi.Pointer<oaa_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<oaa_snapshot>)>()
external ffi.Pointer<ffi.Float> oaa_snapshot_spectrum_peak(
  ffi.Pointer<oaa_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<oaa_snapshot>)>()
external ffi.Pointer<ffi.Float> oaa_snapshot_spectrum_pan(
  ffi.Pointer<oaa_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<oaa_snapshot>)>()
external ffi.Pointer<ffi.Float> oaa_snapshot_scope(
  ffi.Pointer<oaa_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<oaa_snapshot>)>()
external ffi.Pointer<ffi.Float> oaa_snapshot_histogram(
  ffi.Pointer<oaa_snapshot> snapshot,
);

/// Opens `path`, a UTF-8 filename, and identifies its format. Returns NULL if
/// the file cannot be read or is not a format this build decodes — which is a
/// normal outcome for a user dropping an arbitrary file on the window, not an
/// error worth crashing over. Close with oaa_file_close.
///
/// The file is reported at its own sample rate and channel count, and nothing
/// resamples or remixes it: resampling in front of a measurement changes the
/// measurement. Configure the engine from oaa_file_get_info rather than the
/// other way round. A file with more than OAA_MAX_CHANNELS channels opens
/// successfully and reports its true channel count, so that the caller can say
/// what it found instead of guessing; the engine will refuse it.
@ffi.Native<ffi.Pointer<oaa_file> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<oaa_file> oaa_file_open(ffi.Pointer<ffi.Char> path);

@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<oaa_file>, ffi.Pointer<oaa_file_info>)
>()
external int oaa_file_get_info(
  ffi.Pointer<oaa_file> file,
  ffi.Pointer<oaa_file_info> out,
);

/// Reads up to `frames` frames of interleaved float samples into `interleaved`,
/// which must have room for `frames * channels` floats. Returns the number of
/// frames actually read; 0 means end of file.
///
/// Sample values are not clamped. A float WAV may legitimately contain values
/// outside ±1.0, and clamping them here would destroy exactly the overshoots
/// true-peak metering exists to find.
@ffi.Native<
  ffi.Uint64 Function(ffi.Pointer<oaa_file>, ffi.Pointer<ffi.Float>, ffi.Uint64)
>()
external int oaa_file_read(
  ffi.Pointer<oaa_file> file,
  ffi.Pointer<ffi.Float> interleaved,
  int frames,
);

/// Seeks to `frame`. Returns OAA_ERR_UNSUPPORTED if the decoder could not seek,
/// which some malformed or streamed files will do.
///
/// Analysis never uses this — an integrating measurement over a file that was
/// seeked through is a measurement of a programme nobody played. It exists for
/// a future waveform view that needs to read a region without re-reading the
/// whole file.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<oaa_file>, ffi.Uint64)>()
external int oaa_file_seek(ffi.Pointer<oaa_file> file, int frame);

@ffi.Native<ffi.Void Function(ffi.Pointer<oaa_file>)>()
external void oaa_file_close(ffi.Pointer<oaa_file> file);

/// ------------------------------------------------------------------------ */
/// /* Status codes                                                              */
/// /* ------------------------------------------------------------------------
enum oaa_status {
  OAA_OK(0),
  OAA_ERR_INVALID_ARGUMENT(-1),
  OAA_ERR_OUT_OF_MEMORY(-2),
  OAA_ERR_WRONG_STATE(-3),
  OAA_ERR_THREAD(-4),
  OAA_ERR_UNSUPPORTED(-5);

  final int value;
  const oaa_status(this.value);

  static oaa_status fromValue(int value) => switch (value) {
    0 => OAA_OK,
    -1 => OAA_ERR_INVALID_ARGUMENT,
    -2 => OAA_ERR_OUT_OF_MEMORY,
    -3 => OAA_ERR_WRONG_STATE,
    -4 => OAA_ERR_THREAD,
    -5 => OAA_ERR_UNSUPPORTED,
    _ => throw ArgumentError('Unknown value for oaa_status: $value'),
  };
}

/// ------------------------------------------------------------------------ */
/// /* Signal sources                                                            */
/// /* ------------------------------------------------------------------------
enum oaa_source_kind {
  /// Digital black. Useful for asserting that the meters actually fall to their
  /// floor rather than freezing at their last value.
  OAA_SOURCE_SILENCE(0),

  /// An internally generated test signal. This is not a toy: it is how the
  /// render path is benchmarked without an audio device attached, and how CI
  /// exercises the engine on machines that have no sound hardware at all.
  OAA_SOURCE_TEST_TONE(1),

  /// A hardware or loopback capture device. Phase 1.
  OAA_SOURCE_DEVICE(2),

  /// Reserved, and refused by oaa_engine_create. File analysis does not use a
  /// source of its own: the caller opens an oaa_file, creates an
  /// OAA_SOURCE_PUSH engine to match it, and pushes the blocks it decodes. That
  /// is what makes offline analysis the same `oaa_analyse` over the same buffers
  /// as realtime rather than a second path. The value stays allocated so that
  /// nothing else claims 3.
  OAA_SOURCE_FILE(3),

  /// The caller supplies the audio, synchronously, via oaa_engine_push().
  ///
  /// No thread is started and nothing is paced against a clock: a push returns
  /// once the block has been measured. That makes the engine a pure function of
  /// the samples it was given, which is what lets the conformance suite feed it
  /// a signal it constructed and assert on the result — no device, no timing,
  /// no flakiness. It is also the shape file analysis needs, so Phase 5 decodes
  /// into this rather than growing a second path.
  OAA_SOURCE_PUSH(4);

  final int value;
  const oaa_source_kind(this.value);

  static oaa_source_kind fromValue(int value) => switch (value) {
    0 => OAA_SOURCE_SILENCE,
    1 => OAA_SOURCE_TEST_TONE,
    2 => OAA_SOURCE_DEVICE,
    3 => OAA_SOURCE_FILE,
    4 => OAA_SOURCE_PUSH,
    _ => throw ArgumentError('Unknown value for oaa_source_kind: $value'),
  };
}

/// Everything the UI is allowed to draw, as one flat plain-old-data struct.
///
/// Field values are in the units named in each comment. dB values use -INFINITY
/// for true digital silence. A field the current build does not compute is NaN,
/// never zero — zero is a legitimate reading for correlation, balance and
/// several dB quantities, so it cannot double as "no data".
///
/// Layout rules, because dart:ffi reproduces this struct byte for byte:
/// - No pointers. No bitfields. No `bool`. Fixed-size arrays only.
/// - Widest members first, so natural alignment introduces no padding that
/// differs between compilers.
/// - The `reserved` members are explicit padding, named rather than left to
/// the compiler so that adding a float later does not shift every field
/// after it. They are public because a leading underscore would make the
/// generated Dart bindings private and trip the unused-field lint.
/// - Append new fields at the end, and bump OAA_ABI_VERSION when you do.
final class oaa_snapshot extends ffi.Struct {
  /// Increments every time the analysis thread publishes. The reader uses it to
  /// skip repainting when nothing has changed — at 120 fps against a ~47 Hz
  /// measurement rate, most frames have nothing new to say.
  @ffi.Uint64()
  external int generation;

  /// Seconds of signal measured since the last reset. Not wall-clock time: with
  /// a file source this advances far faster than real time, and that is the
  /// point.
  @ffi.Double()
  external double elapsed_seconds;

  @ffi.Uint32()
  external int sample_rate;

  @ffi.Uint32()
  external int channels;

  /// OAA_FLAG_*
  @ffi.Uint32()
  external int flags;

  /// Frames of audio that never reached the measurement, since the last reset.
  ///
  /// This is not a diagnostic counter. Integrated loudness averages every block
  /// since the reset, so a lost second does not make the reading slightly stale
  /// — it makes it an average of a different programme than the one that played.
  /// A non-zero value here means the integrated reading cannot be trusted, and
  /// the UI has to say so rather than quietly showing it.
  ///
  /// Two things land here, because to a measurement they are the same event.
  /// Frames the capture callback had to discard because the analysis thread fell
  /// behind are counted exactly, by the ring that refused them. Frames missed
  /// while the source was stopped (OAA_FLAG_SOURCE_STOPPED) are counted from the
  /// analysis clock instead, so they are approximate — to within the one block
  /// it takes to notice — because a producer that has gone away is not there to
  /// tell anyone what it did not produce. Approximate is the point: the number
  /// exists to prove audio was lost, and a gap reported as zero is a gap the
  /// user never hears about.
  @ffi.Uint32()
  external int dropped_frames;

  /// 400 ms window
  @ffi.Float()
  external double lufs_momentary;

  /// 3 s window
  @ffi.Float()
  external double lufs_short;

  /// gated, since reset
  @ffi.Float()
  external double lufs_integrated;

  /// loudness range, LU
  @ffi.Float()
  external double lra;

  /// max over a 3 s sliding window
  @ffi.Float()
  external double true_peak;

  /// max since reset
  @ffi.Float()
  external double true_peak_max;

  /// max since reset
  @ffi.Float()
  external double sample_peak_max;

  @ffi.Float()
  external double reserved1;

  /// true_peak - lufs_short,      LU
  @ffi.Float()
  external double dr_short;

  /// true_peak_max - lufs_integrated, LU
  @ffi.Float()
  external double dr_integrated;

  /// Crest factor in dB: sample peak minus RMS, both taken over the block just
  /// measured — not the held peak and the smoothed RMS the meters draw. Those
  /// settle at different rates, so their difference drifts on its own: it read
  /// 11.6 dB for a block of DC, where the answer is 0. A sine is 3.0103 dB.
  /// Multichannel reports the peakiest channel.
  @ffi.Float()
  external double crest;

  /// peak to loudness ratio,      LU
  @ffi.Float()
  external double plr;

  /// peak to short-term ratio,    LU
  @ffi.Float()
  external double psr;

  @ffi.Float()
  external double reserved2;

  /// -1 fully out of phase .. +1 mono
  @ffi.Float()
  external double correlation;

  /// -1 hard left .. +1 hard right
  @ffi.Float()
  external double balance;

  /// dBFS, with the meter's hold applied
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Float> peak;

  /// dBFS, with the meter's decay applied
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Float> rms;

  /// VU, 300 ms ballistics, 0 VU = calibration
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Float> vu;

  /// The longest run of consecutive full-scale samples since the last reset —
  /// latched, not live. A live run is zeroed by the next sample below full
  /// scale, so a publish would carry whatever it happened to be at the block
  /// boundary and every clip that ended mid-block would read zero. Non-zero
  /// here means "this channel clipped, and the worst run was this long"; it
  /// stays non-zero until oaa_engine_reset.
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint32> clip;

  /// --- Spectrum, dBFS per log-spaced band ------------------------------- */
  /// /* The most recent FFT frame. Instantaneous, so it is a measurement of a
  /// moment rather than an average of several.
  @ffi.Array.multi([512])
  external ffi.Array<ffi.Float> spectrum;

  /// Peak hold over *every* FFT frame since the last publish, then a 1.5 s hold
  /// and a 12 dB/s fall.
  ///
  /// This is not redundant with a hold the UI could keep itself, and the reason
  /// is worth stating: the analyser runs an FFT every hop, and a publish carries
  /// only the last one. A hold computed from published frames would therefore
  /// miss every transient that landed between them, which is the single thing a
  /// peak hold exists to catch.
  @ffi.Array.multi([512])
  external ffi.Array<ffi.Float> spectrum_peak;

  /// 10th percentile of the gated short-term distribution
  @ffi.Float()
  external double lra_low;

  /// 95th percentile
  @ffi.Float()
  external double lra_high;

  /// relative gate: ungated mean - 20 LU
  @ffi.Float()
  external double lra_gate;

  @ffi.Float()
  external double reserved3;

  /// Energy balance per spectrum band: -1 entirely left, +1 entirely right, 0
  /// centred. Zero for mono, and meaningless for a band with no energy in it —
  /// read `spectrum` first and skip bands at the floor, because the pan of
  /// silence is not a direction.
  @ffi.Array.multi([512])
  external ffi.Array<ffi.Float> spectrum_pan;

  /// The last OAA_SCOPE_POINTS stereo frames, interleaved x=left, y=right,
  /// oldest first. Raw sample values, **not** rotated into goniometer axes:
  /// that rotation is a display choice, and doing it here would bake one
  /// module's convention into the ABI every other consumer has to undo. Mono
  /// publishes the same value in both, which draws the diagonal it should.
  @ffi.Array.multi([2048])
  external ffi.Array<ffi.Float> scope;

  /// Fraction of the gated short-term blocks that fell in each bin, so the bins
  /// sum to 1 and the UI needs no total. All zero before the first gated block
  /// exists.
  @ffi.Array.multi([120])
  external ffi.Array<ffi.Float> histogram;
}

final class oaa_device_info extends ffi.Struct {
  /// Opaque, platform-specific, and stable enough to store in a preset. Pass it
  /// back in oaa_config.device_id.
  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> id;

  /// What to show a human.
  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> name;

  @ffi.Uint32()
  external int channels;

  @ffi.Uint32()
  external int sample_rate;

  /// Non-zero when this is the system's default capture device.
  @ffi.Uint32()
  external int is_default;

  /// Non-zero when this device captures the system's own output rather than a
  /// physical input.
  ///
  /// Set for WASAPI's loopback devices, which report it natively, and for the
  /// macOS process tap offered under OAA_DEVICE_ID_SYSTEM_OUTPUT, which is one
  /// by construction. It stays zero for a *virtual* loopback — BlackHole, a
  /// PipeWire monitor — because those are indistinguishable from a real input
  /// and reporting a guess would be worse than reporting nothing. So: this
  /// labels a device that certainly captures system output, and its absence
  /// says nothing about whether some other device in the list also does.
  @ffi.Uint32()
  external int is_loopback;
}

final class oaa_device_list extends ffi.Opaque {}

final class oaa_config extends ffi.Struct {
  /// 0 asks the source to pick
  @ffi.Uint32()
  external int sample_rate;

  /// 1..OAA_MAX_CHANNELS
  @ffi.Uint32()
  external int channels;

  /// oaa_source_kind
  @ffi.Uint32()
  external int source;

  /// analysis block size; 0 selects a sane default
  @ffi.Uint32()
  external int block_frames;

  /// Which capture device, for OAA_SOURCE_DEVICE. NULL means the system
  /// default, and OAA_DEVICE_ID_SYSTEM_OUTPUT means the system's own output
  /// where that is offered. Copied during oaa_engine_create; the caller need
  /// not keep it.
  external ffi.Pointer<ffi.Char> device_id;
}

final class oaa_engine extends ffi.Opaque {}

/// Decoding a file into blocks of samples, for offline analysis.
///
/// There is deliberately no `oaa_analyse_file()` here. The caller opens a file,
/// creates a OAA_SOURCE_PUSH engine configured to match it, and loops: read a
/// block, push it, read the snapshot. That is more code at the call site than a
/// single function would be, and it buys two things worth more than the
/// brevity.
///
/// The first is that offline analysis is not a second implementation. It runs
/// the identical `oaa_analyse` over identical buffers, so "the offline number
/// equals the realtime number" is true by construction rather than by
/// inspection — which is the whole argument for trusting a file report.
///
/// The second is progress and cancellation. An hour of audio takes seconds to
/// analyse, and a one-shot call would own those seconds with no way to report
/// how far it had got or to be told to stop. The loop belongs to the caller
/// because the user interface belongs to the caller.
///
/// **Push in blocks, not in one call.** The gated loudness measurements are
/// sample-accurate and genuinely independent of block size, but RMS, crest and
/// the VU ballistics are computed per pushed block — pushing an entire file at
/// once yields one RMS reading averaged over the whole programme and a VU
/// needle that moves exactly once. Use the engine's configured `block_frames`
/// and the offline readings match the realtime ones.
enum oaa_file_format {
  OAA_FILE_FORMAT_UNKNOWN(0),

  /// RIFF or RIFX
  OAA_FILE_FORMAT_WAV(1),
  OAA_FILE_FORMAT_AIFF(2),

  /// RIFF's 64-bit successor, for files over 4 GB
  OAA_FILE_FORMAT_RF64(3),

  /// Sony Wave64
  OAA_FILE_FORMAT_W64(4),
  OAA_FILE_FORMAT_FLAC(5),
  OAA_FILE_FORMAT_MP3(6);

  final int value;
  const oaa_file_format(this.value);

  static oaa_file_format fromValue(int value) => switch (value) {
    0 => OAA_FILE_FORMAT_UNKNOWN,
    1 => OAA_FILE_FORMAT_WAV,
    2 => OAA_FILE_FORMAT_AIFF,
    3 => OAA_FILE_FORMAT_RF64,
    4 => OAA_FILE_FORMAT_W64,
    5 => OAA_FILE_FORMAT_FLAC,
    6 => OAA_FILE_FORMAT_MP3,
    _ => throw ArgumentError('Unknown value for oaa_file_format: $value'),
  };
}

final class oaa_file_info extends ffi.Struct {
  @ffi.Uint32()
  external int sample_rate;

  @ffi.Uint32()
  external int channels;

  /// Total frames in the file, or 0 when the decoder could not determine it.
  /// Zero means unknown, never empty: treat it as an indeterminate length
  /// rather than as a file with nothing in it.
  @ffi.Uint64()
  external int frames;

  /// frames / sample_rate. Zero when `frames` is unknown.
  @ffi.Double()
  external double duration_seconds;

  /// oaa_file_format
  @ffi.Uint32()
  external int format;

  /// Bits per sample in the source encoding, or 0 for a lossy format where the
  /// question has no answer. Reported so a file report can describe its input;
  /// the samples themselves always arrive as float regardless.
  @ffi.Uint32()
  external int bits_per_sample;
}

final class oaa_file extends ffi.Opaque {}

const int OAA_ABI_VERSION = 5;

const int OAA_MAX_CHANNELS = 8;

const int OAA_SPECTRUM_BANDS = 512;

const double OAA_SPECTRUM_HZ_LOW = 20.0;

const double OAA_SPECTRUM_HZ_HIGH = 20000.0;

const int OAA_SCOPE_POINTS = 1024;

const int OAA_HISTOGRAM_BINS = 120;

const double OAA_HISTOGRAM_MIN_LUFS = -60.0;

const double OAA_HISTOGRAM_MAX_LUFS = 0.0;

const double OAA_DB_FLOOR = -144.0;

const int OAA_FLAG_RUNNING = 1;

const int OAA_FLAG_LOUDNESS_UNAVAILABLE = 2;

const int OAA_FLAG_SPECTRUM_UNAVAILABLE = 4;

const int OAA_FLAG_OVERRUN = 8;

const int OAA_FLAG_SOURCE_STOPPED = 16;

const int OAA_DEVICE_ID_MAX = 256;

const int OAA_DEVICE_NAME_MAX = 256;

const String OAA_DEVICE_ID_SYSTEM_OUTPUT = 'system-output';

const double OAA_SILENCE_FLOOR = 0.0010000000474974513;

const double OAA_SILENCE_HOLD_SECONDS = 2.0;
