// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// ------------------------------------------------------------------------ */
/// /* Lifecycle                                                                 */
/// /* ------------------------------------------------------------------------
@ffi.Native<ffi.Int32 Function()>()
external int bel_abi_version();

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> bel_version_string();

/// Fills `cfg` with defaults. Call this before overriding fields, so that
/// adding a field to bel_config does not silently leave it at zero in every
/// existing caller.
@ffi.Native<ffi.Void Function(ffi.Pointer<bel_config>)>()
external void bel_config_defaults(ffi.Pointer<bel_config> cfg);

@ffi.Native<ffi.Pointer<bel_engine> Function(ffi.Pointer<bel_config>)>()
external ffi.Pointer<bel_engine> bel_engine_create(ffi.Pointer<bel_config> cfg);

@ffi.Native<ffi.Void Function(ffi.Pointer<bel_engine>)>()
external void bel_engine_destroy(ffi.Pointer<bel_engine> engine);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<bel_engine>)>()
external int bel_engine_start(ffi.Pointer<bel_engine> engine);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<bel_engine>)>()
external int bel_engine_stop(ffi.Pointer<bel_engine> engine);

/// Clears every integrating measurement — integrated loudness, LRA, all the
/// "max since reset" peaks, the clip counters — and restarts the elapsed clock.
/// Momentary values are left alone; they describe the signal, not the session.
@ffi.Native<ffi.Void Function(ffi.Pointer<bel_engine>)>()
external void bel_engine_reset(ffi.Pointer<bel_engine> engine);

/// The stable address of this engine's snapshot. Valid from create() until
/// destroy(), and it never moves. Call it once and keep the pointer; the
/// contents are only meaningful after bel_snapshot_acquire().
@ffi.Native<ffi.Pointer<bel_snapshot> Function(ffi.Pointer<bel_engine>)>()
external ffi.Pointer<bel_snapshot> bel_snapshot_buffer(
  ffi.Pointer<bel_engine> engine,
);

/// Refresh the snapshot from the analysis thread and return its generation.
///
/// This is the only function called every frame, so it is the only one whose
/// cost is worth arguing about. It is a seqlock read: an atomic load, a memcpy
/// of a few kilobytes, and a second atomic load to confirm no writer intervened.
/// It never blocks the analysis thread and it never waits on a mutex.
///
/// Returns the same value as the previous call when nothing new was published,
/// which is the caller's cue to skip repainting.
@ffi.Native<ffi.Uint64 Function(ffi.Pointer<bel_engine>)>()
external int bel_snapshot_acquire(ffi.Pointer<bel_engine> engine);

/// The address of each array field inside a snapshot.
///
/// These exist so that a consumer can build a typed view over the arrays
/// without knowing their byte offsets. dart:ffi can read the scalars through a
/// generated struct definition perfectly well, but the array fields need to
/// reach the canvas as a flat Float32List — `Canvas.drawRawPoints` and
/// `Vertices.raw` take one directly, and going through per-element accessors
/// instead would put 512 bounds-checked loads on the paint path where a single
/// pointer would do.
///
/// Asking the compiler for the offset rather than computing it in Dart is the
/// whole point. A struct layout that differs between the compiler that built
/// the library and the assumptions baked into the bindings does not crash — it
/// reads the wrong field and displays a plausible number, which is the failure
/// mode this project can least afford.
///
/// Call once, at startup, and keep the views: the snapshot never moves.
@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<bel_snapshot>)>()
external ffi.Pointer<ffi.Float> bel_snapshot_peak(
  ffi.Pointer<bel_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<bel_snapshot>)>()
external ffi.Pointer<ffi.Float> bel_snapshot_rms(
  ffi.Pointer<bel_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<bel_snapshot>)>()
external ffi.Pointer<ffi.Float> bel_snapshot_vu(
  ffi.Pointer<bel_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Uint32> Function(ffi.Pointer<bel_snapshot>)>()
external ffi.Pointer<ffi.Uint32> bel_snapshot_clip(
  ffi.Pointer<bel_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<bel_snapshot>)>()
external ffi.Pointer<ffi.Float> bel_snapshot_spectrum(
  ffi.Pointer<bel_snapshot> snapshot,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<bel_snapshot>)>()
external ffi.Pointer<ffi.Float> bel_snapshot_spectrum_peak(
  ffi.Pointer<bel_snapshot> snapshot,
);

/// ------------------------------------------------------------------------ */
/// /* Status codes                                                              */
/// /* ------------------------------------------------------------------------
enum bel_status {
  BEL_OK(0),
  BEL_ERR_INVALID_ARGUMENT(-1),
  BEL_ERR_OUT_OF_MEMORY(-2),
  BEL_ERR_WRONG_STATE(-3),
  BEL_ERR_THREAD(-4),
  BEL_ERR_UNSUPPORTED(-5);

  final int value;
  const bel_status(this.value);

  static bel_status fromValue(int value) => switch (value) {
    0 => BEL_OK,
    -1 => BEL_ERR_INVALID_ARGUMENT,
    -2 => BEL_ERR_OUT_OF_MEMORY,
    -3 => BEL_ERR_WRONG_STATE,
    -4 => BEL_ERR_THREAD,
    -5 => BEL_ERR_UNSUPPORTED,
    _ => throw ArgumentError('Unknown value for bel_status: $value'),
  };
}

/// ------------------------------------------------------------------------ */
/// /* Signal sources                                                            */
/// /* ------------------------------------------------------------------------
enum bel_source_kind {
  /// Digital black. Useful for asserting that the meters actually fall to their
  /// floor rather than freezing at their last value.
  BEL_SOURCE_SILENCE(0),

  /// An internally generated test signal. This is not a toy: it is how the
  /// render path is benchmarked without an audio device attached, and how CI
  /// exercises the engine on machines that have no sound hardware at all.
  BEL_SOURCE_TEST_TONE(1),

  /// A hardware or loopback capture device. Phase 1.
  BEL_SOURCE_DEVICE(2),

  /// Decoded from a file, driven as fast as the CPU allows. Phase 5.
  BEL_SOURCE_FILE(3);

  final int value;
  const bel_source_kind(this.value);

  static bel_source_kind fromValue(int value) => switch (value) {
    0 => BEL_SOURCE_SILENCE,
    1 => BEL_SOURCE_TEST_TONE,
    2 => BEL_SOURCE_DEVICE,
    3 => BEL_SOURCE_FILE,
    _ => throw ArgumentError('Unknown value for bel_source_kind: $value'),
  };
}

/// Everything the UI is allowed to draw, as one flat plain-old-data struct.
///
/// Field values are in the units named in each comment. dB values use -INFINITY
/// for true digital silence. A field the current build does not compute is NaN,
/// never zero — zero is a legitimate reading for correlation, balance and
/// several dB quantities, so it cannot double as "no data".
///
/// Layout rules, because dart:ffi reproduces this struct byte for byte:
/// - No pointers. No bitfields. No `bool`. Fixed-size arrays only.
/// - Widest members first, so natural alignment introduces no padding that
/// differs between compilers.
/// - The `reserved` members are explicit padding, named rather than left to
/// the compiler so that adding a float later does not shift every field
/// after it. They are public because a leading underscore would make the
/// generated Dart bindings private and trip the unused-field lint.
/// - Append new fields at the end, and bump BEL_ABI_VERSION when you do.
final class bel_snapshot extends ffi.Struct {
  /// Increments every time the analysis thread publishes. The reader uses it to
  /// skip repainting when nothing has changed — at 120 fps against a ~47 Hz
  /// measurement rate, most frames have nothing new to say.
  @ffi.Uint64()
  external int generation;

  /// Seconds of signal measured since the last reset. Not wall-clock time: with
  /// a file source this advances far faster than real time, and that is the
  /// point.
  @ffi.Double()
  external double elapsed_seconds;

  @ffi.Uint32()
  external int sample_rate;

  @ffi.Uint32()
  external int channels;

  /// BEL_FLAG_*
  @ffi.Uint32()
  external int flags;

  @ffi.Uint32()
  external int reserved0;

  /// 400 ms window
  @ffi.Float()
  external double lufs_momentary;

  /// 3 s window
  @ffi.Float()
  external double lufs_short;

  /// gated, since reset
  @ffi.Float()
  external double lufs_integrated;

  /// loudness range, LU
  @ffi.Float()
  external double lra;

  /// max over a 3 s sliding window
  @ffi.Float()
  external double true_peak;

  /// max since reset
  @ffi.Float()
  external double true_peak_max;

  /// max since reset
  @ffi.Float()
  external double sample_peak_max;

  @ffi.Float()
  external double reserved1;

  /// true_peak - lufs_short,      LU
  @ffi.Float()
  external double dr_short;

  /// true_peak_max - lufs_integrated, LU
  @ffi.Float()
  external double dr_integrated;

  /// sample peak - RMS,           dB
  @ffi.Float()
  external double crest;

  /// peak to loudness ratio,      LU
  @ffi.Float()
  external double plr;

  /// peak to short-term ratio,    LU
  @ffi.Float()
  external double psr;

  @ffi.Float()
  external double reserved2;

  /// -1 fully out of phase .. +1 mono
  @ffi.Float()
  external double correlation;

  /// -1 hard left .. +1 hard right
  @ffi.Float()
  external double balance;

  /// dBFS, with the meter's hold applied
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Float> peak;

  /// dBFS, with the meter's decay applied
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Float> rms;

  /// VU, 300 ms ballistics, 0 VU = calibration
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Float> vu;

  /// consecutive full-scale samples seen
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint32> clip;

  /// --- Spectrum, dBFS per log-spaced band -------------------------------
  @ffi.Array.multi([512])
  external ffi.Array<ffi.Float> spectrum;

  @ffi.Array.multi([512])
  external ffi.Array<ffi.Float> spectrum_peak;
}

/// ------------------------------------------------------------------------ */
/// /* Configuration                                                             */
/// /* ------------------------------------------------------------------------
final class bel_config extends ffi.Struct {
  /// 0 asks the source to pick
  @ffi.Uint32()
  external int sample_rate;

  /// 1..BEL_MAX_CHANNELS
  @ffi.Uint32()
  external int channels;

  /// bel_source_kind
  @ffi.Uint32()
  external int source;

  /// analysis block size; 0 selects a sane default
  @ffi.Uint32()
  external int block_frames;
}

final class bel_engine extends ffi.Opaque {}

const int BEL_ABI_VERSION = 1;

const int BEL_MAX_CHANNELS = 8;

const int BEL_SPECTRUM_BANDS = 512;

const double BEL_DB_FLOOR = -144.0;

const int BEL_FLAG_RUNNING = 1;

const int BEL_FLAG_LOUDNESS_UNAVAILABLE = 2;

const int BEL_FLAG_SPECTRUM_UNAVAILABLE = 4;
