// SPDX-License-Identifier: GPL-3.0-or-later

import 'dart:convert';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter/widgets.dart';

import 'tokens.dart';

/// A QR code, encoded here rather than by a package.
///
/// The same reasoning as `mdns/dns_message.dart`, which is just enough DNS to
/// advertise and find one service: this is just enough QR to carry one address.
/// Open Audio Analyzer encodes exactly one payload — `oaa://host:port`, well
/// under thirty ASCII characters — so what is actually needed is byte mode at
/// one error-correction level over the low versions, which is a closed problem
/// with a published answer and no judgement in it. What a package would add
/// beyond that is kanji mode, structured append, and a second opinion about how
/// to paint a square.
///
/// **It ships with the conformance test that proves it**, `test/qr_test.dart`,
/// which holds every matrix this class produces against fixtures generated by
/// an independent implementation. That is not ceremony: an encoder with a
/// wrong mask or a transposed format field produces a picture that looks
/// exactly like a QR code and that no camera on earth will read, and there is
/// nothing about the rendered result that reveals it. The failure is
/// indistinguishable from a dirty lens.
///
/// Error correction is fixed at level M — 15 % of the codewords recoverable.
/// L would fit a longer address into a smaller grid and is the wrong trade for
/// a code that is read off a *screen*, at an angle, across a room, by a tablet
/// somebody is holding in one hand.
class QrCode {
  const QrCode._(this.version, this._modules);

  /// The largest version this encoder builds. Version 10 at level M holds 213
  /// bytes; the longest address anybody can generate here — a bracketed IPv6
  /// with a zone and a five-digit port — is under fifty. The ceiling exists so
  /// that [encode] has a defined answer for input that is not an address at
  /// all, not because anything is expected to approach it.
  static const int maxVersion = 10;

  /// 1–[maxVersion]. The side of the square is `4 * version + 17` modules.
  final int version;

  /// Row-major, one byte per module, 1 for dark.
  final Uint8List _modules;

  /// The side of the square, in modules. Not pixels — see [OaaQrCode].
  int get size => version * 4 + 17;

  /// Whether the module at [x], [y] is dark. Origin is the top-left corner.
  bool isDark(int x, int y) => _modules[y * size + x] != 0;

  /// Encodes [text] as a byte-mode QR code, or null if it does not fit.
  ///
  /// Null rather than a throw because every call site is a build method: a
  /// panel that cannot draw a code has something to say instead, and an
  /// exception thrown from `build` takes the whole panel with it.
  static QrCode? encode(String text) {
    final data = utf8.encode(text);

    // The character-count field widens from 8 bits to 16 at version 10, which
    // is why capacity is not a single formula.
    var version = 0;
    for (var v = 1; v <= maxVersion; v++) {
      final capacity = _dataCodewords(v) * 8 - 4 - (v < 10 ? 8 : 16);
      if (data.length * 8 <= capacity) {
        version = v;
        break;
      }
    }
    if (version == 0) return null;

    final bits = _BitBuffer(_dataCodewords(version));
    bits.add(0x4, 4); // Byte mode.
    bits.add(data.length, version < 10 ? 8 : 16);
    for (final byte in data) {
      bits.add(byte, 8);
    }
    bits.pad();

    return QrCode._(version, _draw(version, _interleave(bits.bytes, version)));
  }

  // ---------------------------------------------------------------------------
  // Capacity
  //
  // Two tables of ten entries and three formulae, rather than the four large
  // tables the specification prints. Everything else is derived, so there is
  // one place a typo can hide instead of forty.
  // ---------------------------------------------------------------------------

  /// Error-correction codewords per block, at level M, indexed by version − 1.
  static const List<int> _eccPerBlock = [
    10, 16, 26, 18, 24, 16, 18, 22, 22, 26, //
  ];

  /// Blocks the data is split into, at level M, indexed by version − 1.
  static const List<int> _blockCount = [
    1, 1, 1, 2, 2, 4, 4, 4, 5, 5, //
  ];

  /// Every codeword the symbol holds, data and error correction together.
  ///
  /// The whole square, less the function patterns: two timing lines, three
  /// finders with their separators, the alignment grid, the format fields and —
  /// from version 7 — the two version blocks.
  static int _rawCodewords(int version) {
    var modules = (16 * version + 128) * version + 64;
    if (version >= 2) {
      final aligns = version ~/ 7 + 2;
      modules -= (25 * aligns - 10) * aligns - 55;
      if (version >= 7) modules -= 36;
    }
    return modules ~/ 8;
  }

  static int _dataCodewords(int version) =>
      _rawCodewords(version) -
      _eccPerBlock[version - 1] * _blockCount[version - 1];

  /// The centres of the alignment patterns, evenly spaced from the bottom-right
  /// corner back towards the fixed one at 6.
  static List<int> _alignmentPositions(int version) {
    if (version == 1) return const [];
    final count = version ~/ 7 + 2;
    final step = (version * 4 + count * 2 + 1) ~/ (count * 2 - 2) * 2;
    final result = List<int>.filled(count, 6);
    for (var i = count - 1, pos = version * 4 + 10; i >= 1; i--, pos -= step) {
      result[i] = pos;
    }
    return result;
  }

  // ---------------------------------------------------------------------------
  // Reed–Solomon over GF(256)
  // ---------------------------------------------------------------------------

  /// Multiplication modulo the QR field polynomial, x⁸ + x⁴ + x³ + x² + 1.
  ///
  /// Computed rather than tabled. It runs a few thousand times to build one
  /// code, once, in response to somebody opening a panel — the log tables would
  /// be 768 bytes held for the life of the process to save a microsecond.
  static int _mul(int x, int y) {
    var z = 0;
    for (var i = 7; i >= 0; i--) {
      z = (z << 1) ^ ((z >> 7) * 0x11D);
      z ^= ((y >> i) & 1) * x;
    }
    return z;
  }

  /// The generator polynomial for [degree] error-correction codewords: the
  /// product of (x − 2ⁱ) for i below [degree], with the leading 1 left implicit.
  static Uint8List _divisor(int degree) {
    final result = Uint8List(degree)..[degree - 1] = 1;
    var root = 1;
    for (var i = 0; i < degree; i++) {
      for (var j = 0; j < degree; j++) {
        result[j] = _mul(result[j], root);
        if (j + 1 < degree) result[j] ^= result[j + 1];
      }
      root = _mul(root, 2);
    }
    return result;
  }

  static Uint8List _remainder(Uint8List data, Uint8List divisor) {
    final result = Uint8List(divisor.length);
    for (final byte in data) {
      final factor = byte ^ result[0];
      result.setRange(0, result.length - 1, result, 1);
      result[result.length - 1] = 0;
      for (var i = 0; i < result.length; i++) {
        result[i] ^= _mul(divisor[i], factor);
      }
    }
    return result;
  }

  /// Splits the data into blocks, appends each block's error correction, and
  /// reads the lot back out one codeword per block at a time.
  ///
  /// The interleave is the whole point of the block structure: a coffee ring
  /// over one corner of a printed code damages a few codewords of *every*
  /// block rather than every codeword of one, and each block can lose up to
  /// half its error-correction codewords and still come back.
  static Uint8List _interleave(Uint8List data, int version) {
    final blocks = _blockCount[version - 1];
    final eccLength = _eccPerBlock[version - 1];
    final raw = _rawCodewords(version);

    // The blocks are not all the same size, and the long ones come last. Both
    // facts are load-bearing below: the extra codeword of a long block is read
    // out at the position the short blocks have nothing at.
    final shortBlocks = blocks - raw % blocks;
    final shortLength = raw ~/ blocks;

    final divisor = _divisor(eccLength);
    final grouped = <Uint8List>[];
    for (var i = 0, read = 0; i < blocks; i++) {
      final length = shortLength - eccLength + (i < shortBlocks ? 0 : 1);
      final chunk = Uint8List.sublistView(data, read, read + length);
      read += length;

      final block = Uint8List(shortLength + 1)..setRange(0, length, chunk);
      block.setRange(
        block.length - eccLength,
        block.length,
        _remainder(chunk, divisor),
      );
      grouped.add(block);
    }

    final result = Uint8List(raw);
    for (var i = 0, written = 0; i < grouped[0].length; i++) {
      for (var j = 0; j < blocks; j++) {
        if (i != shortLength - eccLength || j >= shortBlocks) {
          result[written++] = grouped[j][i];
        }
      }
    }
    return result;
  }

  // ---------------------------------------------------------------------------
  // The square
  // ---------------------------------------------------------------------------

  static Uint8List _draw(int version, Uint8List codewords) {
    final size = version * 4 + 17;
    final modules = Uint8List(size * size);

    /// Which modules the data may not be written over. A separate plane rather
    /// than a sentinel value in [modules], because a function module is dark or
    /// light like any other and the two facts are independent.
    final reserved = Uint8List(size * size);

    void put(int x, int y, bool dark) {
      modules[y * size + x] = dark ? 1 : 0;
      reserved[y * size + x] = 1;
    }

    // Timing first, finders over the top of it. The two overlap along the top
    // and left edges and the finder is what has to win there — drawn the other
    // way round, the timing line runs straight through the corner squares and
    // no scanner locates the symbol at all.
    for (var i = 0; i < size; i++) {
      put(6, i, i.isEven);
      put(i, 6, i.isEven);
    }
    for (final (cx, cy) in [(3, 3), (size - 4, 3), (3, size - 4)]) {
      for (var dy = -4; dy <= 4; dy++) {
        for (var dx = -4; dx <= 4; dx++) {
          final x = cx + dx;
          final y = cy + dy;
          if (x < 0 || x >= size || y < 0 || y >= size) continue;
          // Concentric rings: a 3×3 block, a light ring, a dark ring, and the
          // light separator that holds the finder off the data.
          final ring = math.max(dx.abs(), dy.abs());
          put(x, y, ring != 2 && ring != 4);
        }
      }
    }

    final aligns = _alignmentPositions(version);
    for (var i = 0; i < aligns.length; i++) {
      for (var j = 0; j < aligns.length; j++) {
        // The three corners belong to the finders, which are bigger.
        final corner =
            (i == 0 && j == 0) ||
            (i == 0 && j == aligns.length - 1) ||
            (i == aligns.length - 1 && j == 0);
        if (corner) continue;
        for (var dy = -2; dy <= 2; dy++) {
          for (var dx = -2; dx <= 2; dx++) {
            put(
              aligns[i] + dx,
              aligns[j] + dy,
              math.max(dx.abs(), dy.abs()) != 1,
            );
          }
        }
      }
    }

    /// The fifteen format bits, twice: once wrapped around the top-left finder
    /// and once split between the other two, so that the symbol still says what
    /// mask it wears when a quarter of it is unreadable.
    void putFormat(int mask) {
      // Level M is 0b00; the BCH(15, 5) remainder and the 0x5412 mask are the
      // specification's, and the mask is what stops an all-zero format field
      // from being an all-light region a scanner would mistake for quiet zone.
      final data = 0x00 << 3 | mask;
      var remainder = data;
      for (var i = 0; i < 10; i++) {
        remainder = (remainder << 1) ^ ((remainder >> 9) * 0x537);
      }
      final bits = (data << 10 | remainder) ^ 0x5412;
      int bit(int i) => (bits >> i) & 1;

      for (var i = 0; i <= 5; i++) {
        put(8, i, bit(i) == 1);
      }
      put(8, 7, bit(6) == 1);
      put(8, 8, bit(7) == 1);
      put(7, 8, bit(8) == 1);
      for (var i = 9; i < 15; i++) {
        put(14 - i, 8, bit(i) == 1);
      }
      for (var i = 0; i < 8; i++) {
        put(size - 1 - i, 8, bit(i) == 1);
      }
      for (var i = 8; i < 15; i++) {
        put(8, size - 15 + i, bit(i) == 1);
      }
      // The one module that is dark in every symbol ever made.
      put(8, size - 8, true);
    }

    putFormat(0);

    // The version, twice, from version 7 — where the count of possible sizes
    // has grown past what the finders' spacing alone can tell a scanner.
    if (version >= 7) {
      var remainder = version;
      for (var i = 0; i < 12; i++) {
        remainder = (remainder << 1) ^ ((remainder >> 11) * 0x1F25);
      }
      final bits = version << 12 | remainder;
      for (var i = 0; i < 18; i++) {
        final dark = ((bits >> i) & 1) == 1;
        final a = size - 11 + i % 3;
        final b = i ~/ 3;
        put(a, b, dark);
        put(b, a, dark);
      }
    }

    // The data, in a two-module-wide boustrophedon from the bottom-right corner
    // to the top-left, skipping the timing column at 6 and every reserved
    // module on the way. Whatever modules are left over past the last codeword
    // stay light, which is what the specification's remainder bits are.
    var bit = 0;
    for (var right = size - 1; right >= 1; right -= 2) {
      if (right == 6) right = 5;
      for (var vertical = 0; vertical < size; vertical++) {
        for (var j = 0; j < 2; j++) {
          final x = right - j;
          final upward = ((right + 1) & 2) == 0;
          final y = upward ? size - 1 - vertical : vertical;
          if (reserved[y * size + x] == 0 && bit < codewords.length * 8) {
            modules[y * size + x] =
                (codewords[bit >> 3] >> (7 - (bit & 7))) & 1;
            bit++;
          }
        }
      }
    }

    // Eight candidate masks, scored, lowest wins. The mask is not decoration:
    // an unmasked symbol of ordinary text is full of large same-coloured
    // regions and runs that imitate a finder, and either one costs a scanner
    // the lock it needs before it can read a single module.
    void applyMask(int mask) {
      for (var y = 0; y < size; y++) {
        for (var x = 0; x < size; x++) {
          if (reserved[y * size + x] != 0) continue;
          final invert = switch (mask) {
            0 => (x + y) % 2 == 0,
            1 => y % 2 == 0,
            2 => x % 3 == 0,
            3 => (x + y) % 3 == 0,
            4 => (y ~/ 2 + x ~/ 3) % 2 == 0,
            5 => x * y % 2 + x * y % 3 == 0,
            6 => (x * y % 2 + x * y % 3) % 2 == 0,
            _ => ((x + y) % 2 + x * y % 3) % 2 == 0,
          };
          if (invert) modules[y * size + x] ^= 1;
        }
      }
    }

    var best = 0;
    var bestPenalty = -1;
    for (var mask = 0; mask < 8; mask++) {
      applyMask(mask);
      putFormat(mask);
      final penalty = _penalty(modules, size);
      if (bestPenalty < 0 || penalty < bestPenalty) {
        best = mask;
        bestPenalty = penalty;
      }
      applyMask(mask); // Exclusive-or is its own inverse.
    }
    applyMask(best);
    putFormat(best);

    return modules;
  }

  /// How badly a masked symbol reads, by the specification's four rules.
  ///
  /// Only the *ordering* of the eight scores matters, but the weights are the
  /// published ones anyway: they are what an independent encoder scores with,
  /// which is what makes a golden fixture a test of this file rather than a
  /// record of its opinions.
  static int _penalty(Uint8List modules, int size) {
    var result = 0;
    var dark = 0;

    // Rule 1, runs of five or more, and rule 3, the finder-like sequence — both
    // read off the same pass, once along the rows and once down the columns.
    for (var pass = 0; pass < 2; pass++) {
      for (var line = 0; line < size; line++) {
        var runColour = 0;
        var runLength = 0;
        final history = List<int>.filled(7, 0);

        void addHistory(int length) {
          // A symbol is surrounded by quiet zone, and rule 3 counts a run that
          // ends at the edge as though the border were part of it.
          final padded = history[0] == 0 ? length + size : length;
          history.setRange(1, 7, history);
          history[0] = padded;
        }

        // 1 : 1 : 3 : 1 : 1 with four modules of clear space to one side of it,
        // which is the finder pattern's own signature appearing where there is
        // no finder.
        int countPatterns() {
          final n = history[1];
          final core =
              n > 0 &&
              history[2] == n &&
              history[3] == n * 3 &&
              history[4] == n &&
              history[5] == n;
          return (core && history[0] >= n * 4 && history[6] >= n ? 1 : 0) +
              (core && history[6] >= n * 4 && history[0] >= n ? 1 : 0);
        }

        for (var i = 0; i < size; i++) {
          final value = pass == 0
              ? modules[line * size + i]
              : modules[i * size + line];
          if (pass == 0) dark += value;

          if (value == runColour) {
            runLength++;
            if (runLength == 5) {
              result += 3;
            } else if (runLength > 5) {
              result++;
            }
          } else {
            addHistory(runLength);
            if (runColour == 0) result += countPatterns() * 40;
            runColour = value;
            runLength = 1;
          }
        }
        if (runColour != 0) {
          addHistory(runLength);
          runLength = 0;
        }
        addHistory(runLength + size);
        result += countPatterns() * 40;
      }
    }

    // Rule 2: every 2 × 2 block of one colour, counted once per top-left
    // corner, so a 3 × 3 patch is four of them.
    for (var y = 0; y < size - 1; y++) {
      for (var x = 0; x < size - 1; x++) {
        final value = modules[y * size + x];
        if (value == modules[y * size + x + 1] &&
            value == modules[(y + 1) * size + x] &&
            value == modules[(y + 1) * size + x + 1]) {
          result += 3;
        }
      }
    }

    // Rule 4: how far the proportion of dark modules is from half, in steps of
    // five percentage points.
    final total = size * size;
    final steps = ((dark * 20 - total * 10).abs() + total - 1) ~/ total - 1;
    return result + steps * 10;
  }
}

/// The bit stream a byte-mode symbol carries, written straight into the
/// codewords it will become.
class _BitBuffer {
  _BitBuffer(int codewords) : bytes = Uint8List(codewords);

  final Uint8List bytes;
  int _bit = 0;

  void add(int value, int width) {
    for (var i = width - 1; i >= 0; i--) {
      if (((value >> i) & 1) == 1) bytes[_bit >> 3] |= 0x80 >> (_bit & 7);
      _bit++;
    }
  }

  /// Closes the stream: up to four zero bits to say the message has ended, zeros
  /// to the byte boundary, then 0xEC and 0x11 alternating to the end.
  ///
  /// Only the alternating pad is written, because the buffer starts zeroed and
  /// the first two steps write nothing else.
  void pad() {
    final firstPad = (math.min(_bit + 4, bytes.length * 8) + 7) >> 3;
    for (var i = firstPad; i < bytes.length; i++) {
      bytes[i] = (i - firstPad).isEven ? 0xEC : 0x11;
    }
    _bit = bytes.length * 8;
  }
}

/// A [QrCode], painted.
///
/// **This is the one widget in the design system that does not take its colours
/// from the skin, and that is a property of the format rather than a lapse.** A
/// QR code is read by thresholding a camera image: the specification asks for a
/// reflectance difference the decoder can find, and every scanner in the world
/// is built around dark modules on a light field. A code drawn in a dark skin's
/// panel colours is a picture of a QR code — some phones read an inverted
/// symbol, most Android decoders do not, and the ones that do are slower at it
/// while somebody holds a tablet at arm's length. [ink] and [paper] are fixed
/// for the same reason the meters are never allowed to invent a number: what is
/// on screen has to work, not match.
///
/// The quiet zone is part of the symbol, not margin around it. Four modules of
/// [paper] on every side, inside the card, so that placing the code against any
/// panel colour cannot eat it.
class OaaQrCode extends StatelessWidget {
  const OaaQrCode({required this.code, this.size = 220, super.key});

  final QrCode code;

  /// The side of the painted square, including the quiet zone.
  final double size;

  /// Near-black rather than black, which is what every printed instrument face
  /// in this design does, and comfortably inside the contrast the format wants.
  static const Color ink = Color(0xFF15181A);

  /// Near-white for the same reason, and the card the code sits on.
  static const Color paper = Color(0xFFF7F8F8);

  /// Modules of quiet zone on each side. Four is the specification's minimum.
  static const int quietZone = 4;

  @override
  Widget build(BuildContext context) {
    return SizedBox.square(
      dimension: size,
      child: ClipRRect(
        borderRadius: OaaRadius.allSm,
        child: CustomPaint(
          // Not `DecoratedBox`: painted chrome absorbs pointer events unless
          // something stops it, and this sits inside a panel that scrolls.
          painter: _QrPainter(code),
          isComplex: true,
          willChange: false,
        ),
      ),
    );
  }
}

class _QrPainter extends CustomPainter {
  const _QrPainter(this.code);

  final QrCode code;

  @override
  bool? hitTest(Offset position) => false;

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawRect(Offset.zero & size, Paint()..color = OaaQrCode.paper);

    final span = code.size + OaaQrCode.quietZone * 2;
    final scale = size.shortestSide / span;

    // **Snapped to whole device pixels, and the runs merged.** A module drawn at
    // a fractional offset is antialiased into its neighbour on both sides, and
    // a code whose every edge is a grey ramp is one a camera has to threshold
    // twice as hard — which shows up as a symbol that reads instantly on a
    // phone held still and not at all on one that is moving. Merging each row's
    // consecutive dark modules into one rectangle removes the seam between
    // them as well, and takes the draw calls from a few thousand to a few
    // dozen.
    final paint = Paint()..color = OaaQrCode.ink;
    double edge(int index) =>
        ((index + OaaQrCode.quietZone) * scale).roundToDouble();

    for (var y = 0; y < code.size; y++) {
      var run = -1;
      for (var x = 0; x <= code.size; x++) {
        final dark = x < code.size && code.isDark(x, y);
        if (dark && run < 0) {
          run = x;
        } else if (!dark && run >= 0) {
          canvas.drawRect(
            Rect.fromLTRB(edge(run), edge(y), edge(x), edge(y + 1)),
            paint,
          );
          run = -1;
        }
      }
    }
  }

  @override
  bool shouldRepaint(_QrPainter oldDelegate) => oldDelegate.code != code;
}
